// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB1uXPWzS8XvBNiW_HowXOC-FzIOHkFng',
    appId: '1:655072200016:web:13afb3be200ada37b09855',
    messagingSenderId: '655072200016',
    projectId: 'chat-app-15a08',
    authDomain: 'chat-app-15a08.firebaseapp.com',
    storageBucket: 'chat-app-15a08.firebasestorage.app',
    measurementId: 'G-WF1BX4W2YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg08mJ83TORnZZq2n618WXEHtsPJHiPJo',
    appId: '1:655072200016:android:873f557eb2beea2ab09855',
    messagingSenderId: '655072200016',
    projectId: 'chat-app-15a08',
    storageBucket: 'chat-app-15a08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS-c5m2PDC7y0W4M5w4gtt1Zk2C1SY290',
    appId: '1:655072200016:ios:34ff64ae1ebd56f5b09855',
    messagingSenderId: '655072200016',
    projectId: 'chat-app-15a08',
    storageBucket: 'chat-app-15a08.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS-c5m2PDC7y0W4M5w4gtt1Zk2C1SY290',
    appId: '1:655072200016:ios:34ff64ae1ebd56f5b09855',
    messagingSenderId: '655072200016',
    projectId: 'chat-app-15a08',
    storageBucket: 'chat-app-15a08.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB1uXPWzS8XvBNiW_HowXOC-FzIOHkFng',
    appId: '1:655072200016:web:68d9d25be429b88bb09855',
    messagingSenderId: '655072200016',
    projectId: 'chat-app-15a08',
    authDomain: 'chat-app-15a08.firebaseapp.com',
    storageBucket: 'chat-app-15a08.firebasestorage.app',
    measurementId: 'G-BZ59TC8HXC',
  );
}
